<app:view title="Perfil de Usuario">
    <app:row>
        <app:card columnSize="10">
            <app:title-primary text="Bienvenido, {user}">
            <app:action-button route="">Iniciar Prueba con Piano Interactivo</app:action-button>
            <app:action-button route="">Iniciar Prueba Sencilla</app:action-button>
            <app:action-button route="" accent="danger">Cerrar Sesión</app:action-button>
            <app:spacing size="3">
            <app:title-primary text="Mis Resultados">
            
            <for start="1" end="6">
                <app:title-secondary text="Prueba #{i} (08/20/2021 21:04:23)">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Aciertos Totales</th>
                            <th>Aciertos Piano</th>
                            <th>Aciertos Sintéticos</th>
                            <th>Aciertos Naturales</th>
                            <th>Aciertos Sostenidos</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>60 / 60 (100%)</td>
                            <td>30 / 30 (100%)</td>
                            <td>30 / 30 (100%)</td>
                            <td>17 / 17 (100%)</td>
                            <td>13 / 13 (100%)</td>
                        </tr>
                    </tbody>
                </table>

                <table class="table">
                    <thead>
                        <tr>
                            <th>C / DO</th>
                            <th>C# / DO#</th>
                            <th>D / RE</th>
                            <th>D# / RE#</th>
                            <th>E / MI</th>
                            <th>F / FA</th>
                            <th>F# / FA#</th>
                            <th>G / SOL</th>
                            <th>G# / SOL#</th>
                            <th>A / LA</th>
                            <th>A# / LA#</th>
                            <th>B / SI</th>
                        </tr>

                    </thead>
                    <tbody>
                        <tr>
                            <td>100%</td>
                            <td>100%</td>
                            <td>100%</td>
                            <td>100%</td>
                            <td>100%</td>
                            <td>100%</td>
                            <td>100%</td>
                            <td>100%</td>
                            <td>100%</td>
                            <td>100%</td>
                            <td>100%</td>
                            <td>100%</td>
                        </tr>
                    </tbody>
                </table>
                <hr>
            </for>
        </app:card>
    </app:row>
</app:view>