<View title="%%abouttitle%%">
    <ServiceBanner>
    <Container>
        <Row>
            <Column smallSize="12" mediumSize="10" largeSize="8" size="7">
                <Spacing>
                <Image source="logo2.png">
                <Spacing>
                <Card>
                    <Title>
                        %%abouttitle%%
                    </Title>
                    <Label textPosition="justify" fontSize="1.25em">
                        %%about1%%
                        <Spacing> 
                        %%about2%%
                        <MailTo target="gabriela.chavarriasoley@ucr.ac.cr">
                    </Label>
                    <Spacing>
                    <Title>
                        %%about3%%
                    </Title>
                    <Label textPosition="justify" fontSize="1.25em">
                        %%about4%%
                    </Label>
                </Card>
            </Column>
        </Row>
    </Container>
</View>