<View title="">
    <ServiceBanner>
    <Container>
        <Row>
            <Column size="6">
                <Spacing>
                <Image source="logo.png">
                <Spacing>
                <Card maxWidth="600px">
                    <Subtitle>
                        Finalidad
                    </Subtitle>
                    <Label textPosition="justify">
                        Esta prueba de oído absoluto es parte de un proyecto de la investigación de la Universidad de Costa Rica a cargo de la Dra. Gabriela Chavarría.
                        Sus resultados pueden ser utilizados de forma anónima en publicaciones científicas. 
                        <Spacing> 
                        Para cualquier consulta puede escribir al correo 
                        <MailTo target="gabriela.chavarriasoley@ucr.ac.cr">
                    </Label>
                    <Spacing>
                    <Subtitle>
                        Detalles de la prueba
                    </Subtitle>
                    <Label textPosition="justify">
                        La prueba de oído absoluto tiene dos partes, una con notas de piano y otra con tonos puros.  
                        En cada parte de la prueba escuchará 30 tonos con un segundo de duración y luego tendrá tres segundos para identificar la nota que escuchó.  
                        Al concluir la prueba podrá saber cuántas notas identificó correctamente.   
                        Como parte de la prueba se le solicita inicialmente información de contacto e información acerca del instrumento que toca, la edad de inicio de su formación musical, etc.
                    </Label>
                </Card>
            </Column>
        </Row>
    </Container>
</View>