<View title="Términos de uso y condiciones del servicio">
    <ServiceBanner>
    <Spacing>
    <Container>
        <Row>
            <Column size="10" maxWidth="1200px">
                <Card>
                    <Title>
                        TÉRMINOS DE USO Y CONDICIONES DEL SERVICIO
                    </Title>
                    <Spacing>
                    <Subtitle>
                        INFORMACIÓN RELEVANTE
                    </Subtitle>
                    <Label>
                        El uso de nuestros servicios implicará que usted ha leído y aceptado los Términos y Condiciones de Uso en el presente documento de esta sección de la página. 
                        El usuario puede elegir y cambiar la clave para su acceso de administración de su cuenta en cualquier momento, en caso de que se haya registrado y que sea necesario,
                        no obstante nuestro sitio web no asume la responsabilidad en caso de que entregue dicha clave a terceros.
                    </Label>
                    <Spacing>
                    <Subtitle>
                        PRIVACIDAD
                    </Subtitle> 
                    <Label>
                        Este garantiza que la información personal que usted envía cuenta con la seguridad necesaria. Los datos ingresados son recolectados para fines investigativos
                        y solo serán compartidos en el caso de cumplimiento a una orden judicial o requerimientos legales.
                    </Label>
                    <Spacing>
                    <Subtitle>
                        USO NO AUTORIZADO
                    </Subtitle> 
                    <Label>
                        En caso de que aplique (para venta de software, distribución, u otro producto de diseño y programación) usted no puede colocar uno de nuestros productos, 
                        modificado o sin modificar, en un CD, sitio web o ningún otro medio y ofrecerlos para la redistribución o la reventa de ningún tipo.
                    </Label>
                    <Spacing>
                    <Subtitle>
                        PROPIEDAD
                    </Subtitle> 
                    <Label>
                        Usted no puede declarar propiedad intelectual o exclusiva a ninguno de nuestros productos, modificado o sin modificar. 
                        En caso de que no se especifique lo contrario, nuestros productos se proporcionan sin ningún tipo de garantía, expresa o implícita. 
                        En ningún caso esta compañía será responsable de ningún tipo de daño incluyendo, pero no limitado a, daños directos, 
                        indirectos, especiales, fortuitos o consecuentes u otras pérdidas resultantes del uso o de la imposibilidad de utilizar nuestros productos.
                    </Label>
                </Card>
            </Column>
        </Row>
    </Container>
</View>