<app:view title="Cambio de contraseña">
    <app:row>
        <app:card columnSize="8" maxWidth="600px">
            <app:form route="newpass/submit">
                <app:title-icon imageSource="profile.png" text="Cambio de contraseña">
                <app:label for="password">Porfavor, ingrese la nueva contraseña</app:label> 
                <app:passfield>
                <app:label for="confirm_password">Confirme la contraseña</app:label> 
                <app:passfield bind="confirm_password">
                <app:submit-button>Actualizar contraseña</app:submit-button>
                <app:spacing>
                <app:span>Después de actualizar su contraseña, debera iniciar sesión nuevamente.</app:span>
            </app:form>
        </app:card>
    </app:row>
</app:view>
<script> 
    $(document).ready(function() {
        
    });
</script>