<app:row>
    PARTE 1
</app:row>
<app:row>
    PARTE 2
    <app:row>
        PARTE 3
        <app:row>
            PARTE 4
            <app:card columnSize="3" padding="1">
                PARTE 5
                <app:card columnSize="3" padding="1">
                    PARTE 6
                </app:card>
                PARTE 7
            </app:card>
            PARTE 8
        </app:row>
        PARTE 9
    </app:row>
    PARTE 10
</app:row>