<app:view title="Recolección de información">
    <app:row>
        <app:card columnSize="10">
            <app:title-primary text="Recolección de información">
            <app:title-secondary text="Se le pedirá que conteste el siguiente formulario sinceramente:">
            <foreach name="question" from="view:questions">
                <div>Pregunta: {question:subject}</div>
                <div>Tipo: {question:type}</div>
            </foreach>
        </app:card>
    </app:row>
</app:view>