<app:view title="Inicio de sesión">
    <app:row>
        <app:card columnSize="8" maxWidth="600px">
            <app:form route="login/submit">
                <app:title-icon imageSource="profile.png" text="Inicio de sesión">
                <app:span>Sírvase de acceder al servicio para realizar o consultar su historial de pruebas</app:span>
                <app:label for="email"> Correo Electrónico</app:label> 
                <app:textfield bind="email">
                <app:label for="password">Contraseña</app:label>   
                <app:passfield>
                <app:submit-button>Acceder al Proyecto</app:submit-button>
                <app:action-button route="signup">O bien, Crear cuenta</app:action-button>
                <app:spacing>
                <app:span>¿Olvidó su contraseña o no puede acceder a su cuenta?</app:span>
                <app:action-link route="forgot">Haga click en este enlace para recuperar su contraseña</app:action-link>
            </app:form>
        </app:card>
    </app:row>
</app:view>
<script> 
    $(document).ready(function() {
        $("#form").validate({
            rules: {
                email: {
                    required: true,
                    email: true
                },
                password: {
                    required: true,
                    minlength: 7,
                    maxlength: 24
                }
            },
            messages : {
                email: {
                    required: "El campo debe contener un correo electrónico",
                    email: "El formato correcto es: abc@domain.com"
                },
                password: {
                    required: "El campo de contraseña no puede estar vacio",
                    minlength: "La contraseña debe ser de al menos de 7 carácteres",
                    maxlength: "Demasiada extenso"
                }
            }
        });
    });
</script>