<View title="Cambio de contraseña">
    <ServiceBanner>
    <Container>
        <Row>
            <Column size="6">
                <Spacing>
                <Image source="logo2.png">
                <Spacing>
                <Card maxWidth="600px">
                    <Form id="resetPasswordForm" route="newpass/submit">
                        <HiddenField id="token" value="{token}">
                        <IconifiedTitle source="profile.png">
                            Cambio de contraseña
                        </IconifiedTitle>
                        <Label for="password">
                            Porfavor, ingrese la nueva contraseña
                        </Label> 
                        <Passfield id="password">
                        <Label for="confirmPassword">
                            Confirme la contraseña
                        </Label> 
                        <Passfield id="confirmPassword">
                        <SubmitButton>
                            Actualizar contraseña
                        </SubmitButton>
                        <Spacing>
                        <Span>
                            Después de actualizar su contraseña, debera iniciar sesión nuevamente.
                        </Span>
                    </Form>
                </Card>
            </Column>
        </Row>
    </Container>
</View>