<View title="Cambio de contraseña">
    <ServiceBanner>
    <Container>
        <Row>
            <Column size="6">
                <Spacing>
                <Image source="logo2.png">
                <Spacing>
                <Card maxWidth="600px">
                    <Form id="resetPasswordForm" route="newpass/submit">
                        <HiddenField id="token" value="{token}">
                        <IconifiedTitle source="profile.png">
                            Cambio de contraseña
                        </IconifiedTitle>
                        <Label for="password">
                            Porfavor, ingrese la nueva contraseña
                        </Label> 
                        <Passfield id="password">
                        <Label for="confirmPassword">
                            Confirme la contraseña
                        </Label> 
                        <Passfield id="confirmPassword">
                        <SubmitButton>
                            Actualizar contraseña
                        </SubmitButton>
                        <Spacing>
                        <Span>
                            Después de actualizar su contraseña, debera iniciar sesión nuevamente.
                        </Span>
                    </Form>
                </Card>
            </Column>
        </Row>
    </Container>
    <script type="text/javascript">
        $("#resetPasswordForm").validate({
            rules: {
                password: {
                    required: true,
                    minlength: 7,
                    maxlength: 24
                },
                confirmPassword: {
                    required: true,
                    equalTo: "#password",
                    minlength: 7,
                    maxlength: 24
                },
            },
            messages: {
                password: {
                    required: "El campo de contraseña no puede estar vacio",
                    minlength: "La contraseña debe ser de al menos de 7 carácteres",
                    maxlength: "Demasiada extenso"
                },
                confirmPassword: {
                    required: "La contraseña no puede estar vacio",
                    equalTo: "Ambas contraseñas deben coincidir",
                    minlength: "La contraseña debe ser de al menos de 7 carácteres",
                    maxlength: "Demasiada extenso"
                },
            }
        });
    </script>
</View>