<app:view title="Recuperación de Contraseña">
    <app:row>
        <app:card columnSize="8" maxWidth="600px">
            <app:form route="forgot/submit">
                <app:title-icon imageSource="profile.png" text="Recuperación de Contraseña">
                <h6>¿Problemas para acceder a su cuenta?</h6>
                <app:spacing>
                <app:label for="email">Correo Electrónico</app:label>  
                <app:textfield bind="email">
                <app:span>
                    Si el correo se encuentra previamente registrado en nuestra base de datos, 
                    se le enviará un correo a esa direccion con las instrucciones de recuperación.
                </app:span>
                <app:spacing>
                <app:submit-button>Enviar correo electrónico</app:submit-button>
                <app:spacing>
            </app:form>
        </app:card>
    </app:row>
</app:view>
<script> 
    $(document).ready(function() {
        $("#form").validate({
            rules: {
                email: {
                    required: true,
                    email: true
                },
            },
            messages : {
                email: {
                    required: "El campo debe contener un correo electrónico",
                    email: "El formato correcto es: abc@domain.com"
                }
            }
        });
    });
</script>