<v-view title="Cambio de contraseña">
    <v-card size="12" maxWidth="600px">
        <v-title-icon img="profile.png" text="Cambio de contraseña">
        <v-form route="newpass/submit">
            <v-label for="password">Porfavor, ingrese la nueva contraseña</v-label>   
            <v-password>
            <v-label for="confirm_password">Porfavor, ingrese la nueva contraseña</v-label>   
            <v-password bind="confirm_password"><br>
            <v-submit-button>Actualizar contraseña</v-submit-button>
            <v-spacing size="2">
            <v-span>Después de actualizar su contraseña, debera iniciar sesión nuevamente.</v-span>
        </v-form>
    </v-card>
</v-view>
<script> 
    $(document).ready(function() {
        $("#form").validate({
            rules: {
                password: {
                    required: true,
                    minlength: 7,
                    maxlength: 24
                },
                confirm_password: {
                    required: true,
                    equalTo: "#password",
                    minlength: 7,
                    maxlength: 24
                },
            },
            messages : {
                password: {
                    required: "El campo de contraseña no puede estar vacio",
                    minlength: "La contraseña debe ser de al menos de 7 carácteres",
                    maxlength: "Demasiada extenso"
                },
                confirm_password: {
                    required: "La contraseña no puede estar vacio",
                    equalTo: "Ambas contraseñas deben coincidir",
                    minlength: "La contraseña debe ser de al menos de 7 carácteres",
                    maxlength: "Demasiada extenso"
                },
            }
        });
    });
</script>