<v-view title="Recuperación de Contraseña">
    <v-card size="12" maxWidth="600px">
        <v-title-icon img="profile.png" text="Recuperación de Contraseña">
        <v-form route="reset_request_submit">
            <h6>¿Problemas para acceder a su cuenta?</h6>
            <v-spacing size="2">
            <v-label for="email">Correo Electrónico</v-label>  
            <v-textbox bind="email">
            <v-span>
                Si el correo se encuentra previamente registrado en nuestra base de datos, 
                se le enviará un correo a esa direccion con las instrucciones de recuperación.
            </v-span> 
            <v-submit-button>Enviar correo electrónico</v-submit-button>
            <v-spacing size="2">
        </v-form>
    </v-card>
</v-view>
<script> 
    $(document).ready(function() {
        $("#reset_request_submit").validate({
            rules: {
                email: {
                    required: true,
                    email: true
                },
            },
            messages : {
                email: {
                    required: "El campo debe contener un correo electrónico",
                    email: "El formato correcto es: abc@domain.com"
                }
            }
        });
    });
</script>