<View title="Cambio de contraseña">
    <Row>
        <Card size="8" maxWidth="600px">
            <Form route="newpass/submit">
                <IconifiedTitle source="profile.png">Cambio de contraseña</IconifiedTitle>
                <Label for="password">Porfavor, ingrese la nueva contraseña</Label> 
                <Passfield>
                <Label for="confirmPassword">Confirme la contraseña</Label> 
                <Passfield bind="confirmPassword">
                <SubmitButton>Actualizar contraseña</SubmitButton>
                <Spacing>
                <Span>Después de actualizar su contraseña, debera iniciar sesión nuevamente.</Span>
            </Form>
        </Card>
    </Row>
</View>