<View title="Recuperación de Contraseña">
    <ServiceBanner>
    <Container>
        <Row>
            <Column size="6">
                <Spacing>
                <Image source="logo2.png">
                <Spacing>
                <Card maxWidth="600px">
                    <Form id="resetRequestForm" route="forgot/submit">
                        <IconifiedTitle source="profile.png">
                            Recuperación de Contraseña
                        </IconifiedTitle>
                        <h6>
                            ¿Problemas para acceder a su cuenta?
                        </h6>
                        <Spacing>
                        <Label for="email">
                            Correo Electrónico
                        </Label>  
                        <Textfield id="email">
                        <Span>
                            Si el correo se encuentra previamente registrado en nuestra base de datos, 
                            se le enviará un correo a esa dirección con las instrucciones de recuperación.
                        </Span>
                        <Spacing>
                        <SubmitButton>
                            Enviar correo electrónico
                        </SubmitButton>
                        <Spacing>
                    </Form>
                </Card>
            </Column>
        </Row>
    </Container>
    <script type="text/javascript">
        $("#resetRequestForm").validate({
            rules: {
                email: {
                    required: true,
                    email: true
                },
            },
            messages: {
                email: {
                    required: "El campo debe contener un correo electrónico",
                    email: "El formato correcto es: abc@domain.com"
                }
            }
        });
    </script>
</View>