<View title="%%recovertitle%%">
    <ServiceBanner>
    <Container>
        <Row>
            <Column size="6">
                <Spacing>
                <Image source="logo2.png">
                <Spacing>
                <Card maxWidth="600px">
                    <Form id="resetRequestForm" route="forgot/submit">
                        <IconifiedTitle source="profile.png">
                            %%recovertitle%%
                        </IconifiedTitle>
                        <h6>
                            %%problems%%
                        </h6>
                        <Spacing>
                        <Label for="email">
                            %%email%%
                        </Label>  
                        <Textfield id="email">
                        <Span>
                            %%resethint%%
                        </Span>
                        <Spacing>
                        <SubmitButton>
                            %%sendmail%%
                        </SubmitButton>
                        <Spacing>
                    </Form>
                </Card>
            </Column>
        </Row>
    </Container>
</View>