<View title="%%signuptitle%%">
    <Container>
        <Row>
            <Column>
                <Card size="8" maxWidth="600px">
                    <Form id="signupForm" route="signup/submit">
                        <IconifiedTitle source="signup.png">
                            %%signuptitle%%
                        </IconifiedTitle>
                        <Spacing>
                        <PersistentMessage>
                        <Container>
                            <Row>
                                <Column smallSize="12" mediumSize="6" size="6" padding="0" textPosition="left">
                                    <Label for="firstName">
                                        %%firstName%%
                                    </Label>
                                    <Textfield id="firstName">
                                </Column>
                                <Column smallSize="12" mediumSize="6" size="6" padding="0" textPosition="left">
                                    <Label for="lastName">
                                        %%lastName%%
                                    </Label>
                                    <Textfield id="lastName">
                                </Column>
                            </Row>
                        </Container>
                        <Label for="email">
                            %%email%%
                        </Label>
                        <Textfield id="email">
                        <Label for="password">
                            %%password%%
                        </Label>
                        <Passfield id="password">
                        <Hint>
                            %%passhintfull%%
                        </Hint>
                        <Spacing>
                        <Label for="confirmPassword">
                            %%confirmpass%%
                        </Label>
                        <Passfield id="confirmPassword">
                        <Label for="country">
                            %%country%%
                        </Label> 
                        <Select id="country" from="{countries}">
                        <Container>
                            <Row>
                                <Column smallSize="6" mediumSize="6" size="6" textPosition="left">
                                    <Label for="birthDay">
                                        %%birthDay%%
                                    </Label>
                                    <Date id="birthDay">
                                    <ErrorContainer id="birthDay">
                                </Column>
                                <Column smallSize="6" mediumSize="6" size="6" textPosition="right">
                                    <Label for="phone">
                                        %%phone%%
                                    </Label>
                                    <Textfield id="phone">
                                </Column>
                            </Row>
                        </Container>
                        <Label for="gender">
                            %%selectGender%%
                        </Label>
                        <Spacing>
                        <Radio id="gender" option="0" text="%%male%%" value="M">
                        <Radio id="gender" option="1" text="%%female%%" value="F">
                        <Radio id="gender" option="2" text="%%other%%" value="O">
                        <Radio id="gender" option="3" text="%%notanswer%%" value="-">
                        <ErrorContainer id="gender">
                        <SubmitButton id="submit">
                            %%signup%%
                        </SubmitButton>
                    </Form>
                </Card>
            </Column>
        </Row>
    </Container>
</View>