<View title="Registro de usuario en el proyecto">
    <Row>
        <Card size="8" maxWidth="600px">
            <Form id="signupForm" route="signup/submit">
                <IconifiedTitle source="signup.png">
                    Registro de usuario
                </IconifiedTitle>
                <Spacing>
                <PersistentError>
                <Row>
                    <Column size="6">
                        <Label for="firstName">
                            Nombre
                        </Label>
                        <Textfield id="firstName">
                    </Column>
                    <Column size="6">
                        <Label for="lastName">
                            Apellidos
                        </Label>
                        <Textfield id="lastName">
                    </Column>
                </Row>
                <Label for="email">
                    Correo Electrónico (Nombre de la cuenta)
                </Label>
                <Textfield id="email">
                <Label for="password">
                    Contraseña
                </Label>
                <Passfield id="password">
                <Hint>
                    La contraseña solo puede contener letras, números y los siguientes simbolos: # @ . -
                </Hint>
                <Spacing>
                <Label for="confirmPassword">
                    Confirmar contraseña
                </Label>
                <Passfield id="confirmPassword">
                <Label for="country">
                    País de nacimiento
                </Label> 
                <Select id="country" from="{countries}">
                <Row>
                    <Column size="6">
                        <Label for="birthDay">
                            Fecha de nacimiento
                        </Label>
                        <Date id="birthDay">
                        <ErrorContainer id="birthDay">
                    </Column>
                    <Column size="6">
                        <Label for="phone">
                            Teléfono
                        </Label>
                        <Textfield id="phone">
                    </Column>
                </Row>
                <Label for="gender">
                    Seleccione su Género
                </Label>
                <Spacing>
                <Radio id="gender" option="0" text="Masculino" value="M">
                <Radio id="gender" option="1" text="Femenino" value="F">
                <Radio id="gender" option="2" text="Otro" value="O">
                <Radio id="gender" option="3" text="No responder" value="-">
                <ErrorContainer id="gender">
                <SubmitButton id="submit">
                    Registrarse
                </SubmitButton>
            </Form>
        </Card>
    </Row>
</View>