<View title="Registro de usuario en el proyecto">
    <Container>
        <Row>
            <Column>
                <Card size="8" maxWidth="600px">
                    <Form id="signupForm" route="signup/submit">
                        <IconifiedTitle source="signup.png">
                            Registro de usuario
                        </IconifiedTitle>
                        <Spacing>
                        <PersistentMessage>
                        <Container>
                            <Row>
                                <Column smallSize="12" mediumSize="6" size="6" padding="0" textPosition="left">
                                    <Label for="firstName">
                                        Nombre
                                    </Label>
                                    <Textfield id="firstName">
                                </Column>
                                <Column smallSize="12" mediumSize="6" size="6" padding="0" textPosition="left">
                                    <Label for="lastName">
                                        Apellidos
                                    </Label>
                                    <Textfield id="lastName">
                                </Column>
                            </Row>
                        </Container>
                        <Label for="email">
                            Correo Electrónico (Nombre de la cuenta)
                        </Label>
                        <Textfield id="email">
                        <Label for="password">
                            Contraseña
                        </Label>
                        <Passfield id="password">
                        <Hint>
                            La contraseña solo puede contener letras, números y los siguientes simbolos: # @ . -
                        </Hint>
                        <Spacing>
                        <Label for="confirmPassword">
                            Confirmar contraseña
                        </Label>
                        <Passfield id="confirmPassword">
                        <Label for="country">
                            País de nacimiento
                        </Label> 
                        <Select id="country" from="{countries}">
                        <Container>
                            <Row>
                                <Column smallSize="6" mediumSize="6" size="6" textPosition="left">
                                    <Label for="birthDay">
                                        Fecha de nacimiento
                                    </Label>
                                    <Date id="birthDay">
                                    <ErrorContainer id="birthDay">
                                </Column>
                                <Column smallSize="6" mediumSize="6" size="6" textPosition="right">
                                    <Label for="phone">
                                        Teléfono
                                    </Label>
                                    <Textfield id="phone">
                                </Column>
                            </Row>
                        </Container>
                        <Label for="gender">
                            Seleccione su Género
                        </Label>
                        <Spacing>
                        <Radio id="gender" option="0" text="Masculino" value="M">
                        <Radio id="gender" option="1" text="Femenino" value="F">
                        <Radio id="gender" option="2" text="Otro" value="O">
                        <Radio id="gender" option="3" text="No responder" value="-">
                        <ErrorContainer id="gender">
                        <SubmitButton id="submit">
                            Registrarse
                        </SubmitButton>
                    </Form>
                </Card>
            </Column>
        </Row>
    </Container>
    <script type="text/javascript">
    $('#signupForm').submit(function (event) {
        if (!Validator.validateDate("birthDay")) {
            event.preventDefault();
            return false;
        }

        if(!$('#signupForm').valid()){
            event.preventDefault();
            return false;
        }

        Validator.disableDateSubComponents("birthDay");

        $('#submit').prop("disabled", true);
        $('#submit').html("Subiendo formulario...");

        
        
    });

    $("#signupForm").validate({
        rules: {
            firstName: {
                required: true,
                minlength: 3
            },
            lastName: {
                required: true,
                minlength: 4
            },
            email: {
                required: true,
                email: true
            },
            password: {
                required: true,
                minlength: 7,
                maxlength: 24
            },
            confirmPassword: {
                required: true,
                equalTo: "#password",
                minlength: 7,
                maxlength: 24
            },
            phone: {
                required: true,
                number: true,
                minlength: 7,
                maxlength: 13
            },
            gender: {
                required: true
            },
            country: {
                required: true
            }
        },
        messages: {
            firstName: {
                required: "El campo del nombre no puede estar vacio",
                minlength: "El nombre debe de ser al menos de 3 carácteres"
            },
            lastName: {
                required: "El campo del apellido no puede estar vacio",
                minlength: "El nombre debe de ser al menos de 3 carácteres"
            },
            email: {
                required: "El campo del email no puede estar vacio",
                email: "El formato correcto es: abc@domain.com"
            },
            password: {
                required: "La contraseña no puede estar vacio",
                minlength: "La contraseña debe ser de al menos de 7 carácteres",
                maxlength: "Demasiada extenso"
            },
            confirmPassword: {
                required: "La contraseña no puede estar vacio",
                equalTo: "Ambas contraseñas deben coincidir",
                minlength: "La contraseña debe ser de al menos de 7 carácteres",
                maxlength: "Demasiada extenso"
            },
            phone: {
                required: "El campo de teléfono no puede estar vacio",
                number: "Debe ser un valor numérico",
                minlength: "Demasiado corto",
                maxlength: "Demasiado extenso"
            },
            gender: {
                required: "Debe seleccionar una opción"
            },
            country: {
                required: "Debe seleccionar una opción"
            }
        }
    });
    </script>
</View>