<app:view title="{view:title}">
    <app:row>
        <app:card columnSize="8" padding="4">
            <app:title-primary text="{view:title}">
            <app:span fontSize="0.9rem">
                <strong>Instrucciones de utilización</strong>
                <app:spacing>
                Una vez usted escucha una nota músical, tiene un intervalo breve de 3 segundos para
                identificar y marcar la nota que cree que escuchó en el {view:title}.
                <if value="{view:showKeyBinds}">
                    Las notas pueden ser marcadas adicionalmente mediante el uso de teclas. 
                    Para el caso de notas blancas, utilice las teclas [ZXCVBNM] y para las negras utilice [SDGHJ].
                </if>
                <v-spacing size="2">
                Cuando se reproduzcan {?note_max} notas consecutivas, se pasará automaticamente a la siguiente etapa.
            </app:span>
            
            <app:spacing>
            <app:col textPosition="center">
                <app:piano pianoMode="{view:mode}">
                    <app:piano-key keyColor="white" noteName="C"  pianoMode="{view:mode}">
                    <app:piano-key keyColor="black" noteName="CX" pianoMode="{view:mode}">
                    <app:piano-key keyColor="white" noteName="D"  pianoMode="{view:mode}">
                    <app:piano-key keyColor="black" noteName="DX" pianoMode="{view:mode}">
                    <app:piano-key keyColor="white" noteName="E"  pianoMode="{view:mode}">
                    <app:piano-key keyColor="white" noteName="F"  pianoMode="{view:mode}">
                    <app:piano-key keyColor="black" noteName="FX" pianoMode="{view:mode}">
                    <app:piano-key keyColor="white" noteName="G"  pianoMode="{view:mode}">
                    <app:piano-key keyColor="black" noteName="GX" pianoMode="{view:mode}">
                    <app:piano-key keyColor="white" noteName="A"  pianoMode="{view:mode}">
                    <app:piano-key keyColor="black" noteName="AX" pianoMode="{view:mode}">
                    <app:piano-key keyColor="white" noteName="B"  pianoMode="{view:mode}">
                </app:piano>
            </app:col>
        </app:card>
        <app:card columnSize="4" padding="4">
            <app:title-primary text="Prueba Auditiva">
            <app:card id="progress_log" padding="3">      
                Tipo de sonido: {?note_type}
                <app:spacing>
                Reproduciendo la nota {?note_current} de {?note_max}
                <app:spacing>
                Tiempo total transcurido: {?time_current_string}
            </app:card>

            <app:spacing>
            <app:script-button id="piano-button" onclick="togglePiano()">{?button_running_string}</app:script-button>
            <app:spacing>
            <app:title-secondary id="piano_log_title" text="Historial de Notas">
            <app:card id="piano_log" columnSize="4" padding="1" accent="secondary" overflow="auto">
                <app:card id="note_log_template" padding="2"></app:card>
            </app:card>

        </app:card>
    </app:row>
</app:view>
<script type="application/json" id="audios_sources">
    {view:audios_sources}
</script>
<script type="text/javascript" src="{view:script}" data-url="{view:url}" data-mode="{view:mode}"></script>