<View title="Perfil de Usuario">
    <ServiceBanner>
    <Spacing>
    <Container>
        <Row>
            <Column smallSize="12" mediumSize="12" size="9" xlSize="8">
                <Card>
                    <IconifiedTitle source="lookup.png">
                        %%lookup1%% {userInfo.firstName} {userInfo.lastName}
                    </IconifiedTitle>
                    <PersistentMessage>
                    <Label>
                       %%lookup2%%
                    </Label>
                    <Spacing>
                    <RedirectButton route="profile">
                        <i class="fa fa-arrow-left fa-lg pr-2" aria-hidden="true"></i>
                        %%lookup3%%
                    </RedirectButton>
                    <RedirectButton route="lookup/exportUserTests?userToken={userToken}" disabled="{noTests}">
                        <i class="fa fa-file-archive-o fa-lg pr-2" aria-hidden="true"></i>
                        %%lookup4%%
                    </RedirectButton>
                    <RedirectButton accent="Success" route="lookup/exportSurvey?userToken={userToken}" disabled="{disableSurvey}">
                        <i class="fa fa-list fa-lg pr-2" aria-hidden="true"></i>
                        %%lookup5%%
                    </RedirectButton>
                    <If value="{userRole}" notEquals="{adminRoleId}">
                        <RedirectButton accent="Info" route="roleChange?to={adminRoleId}&userToken={userToken}">
                            <i class="fa fa-user fa-lg pr-2" aria-hidden="true"></i>
                            %%lookup6%%
                        </RedirectButton>
                    </If>
                    <If value="{userRole}" notEquals="{userRoleId}">
                        <RedirectButton accent="Info" route="roleChange?to={userRoleId}&userToken={userToken}">
                            <i class="fa fa-user fa-lg pr-2" aria-hidden="true"></i>
                            %%lookup7%%
                        </RedirectButton>
                    </If>
                    <Spacing>
                    <Subtitle class="font-weight-bold">
                        %%lookup8%%
                    </Subtitle>
                    <Card padding="3">
                        <div>
                            <strong>
                                %%lookup9%%:
                            </strong> 
                            {userInfo.birthDay}
                        </div>
                        <div>
                            <strong>
                                %%lookup010%%:
                            </strong>
                            {userInfo.country}
                        </div>
                        <div>
                            <strong>
                                %%lookup011%%:
                            </strong> 
                            {userInfo.phone}
                        </div>
                        <div>
                            <strong>
                                %%lookup012%%:
                            </strong> 
                            {userInfo.gender}
                        </div>
                    </Card>
                    <Spacing>
                    <Title>
                        %%lookup013%%
                    </Title>
                    <If value="{noTests}" equals="true">
                        %%lookup014%%
                    </If>
                    <If value="{noTests}" equals="false">
                        <Label>
                        %%lookup015%%
                        <Spacing>
                        %%lookup016%%
                        </Label>
                        <Spacing>
                            <Row>
                                <Column smallSize="12" mediumSize="12" size="12" xlSize="12" padding="1">
                                    <Card padding="2">
                                        <div class="table-responsive">
                                            <table class="table table-sm">
                                                <tr>
                                                    <th>%%lookup017%%</th>
                                                    <th>%%lookup018%%</th>
                                                    <th>%%lookup019%%</th>
                                                    <th>%%lookup020%%</th>
                                                </tr>
                                                <Foreach from="{tests}" using="i">
                                                    <tr id="row-{parent.i.try}" (click)="window.location = '{host}overview?testToken={parent.i.token}'" class="Hover">
                                                        <td>
                                                            {parent.i.try}
                                                        </td>
                                                        <td>
                                                            {parent.i.uploadDate}
                                                        </td>
                                                        <td>
                                                            {parent.i.displayMode}
                                                        </td>
                                                        <td>
                                                            {parent.i.totalTime}
                                                        </td>
                                                    </tr>
                                                </Foreach>
                                            </table>
                                        </div>
                                    </Card>
                                </Column>
                            </Row>
                        <Spacing>
                    </If>
                </Card>
            </Column>
        </Row>
    </Container>
</View>