<View title="%%overview00%%">
    <ServiceBanner>
    <Spacing>
    <Container>
        <Row>
            <Column smallSize="12" mediumSize="12" size="12" xlSize="11">
                <Card>
                    <Title>
                        %%overview01%%
                    </Title>
                    <PersistentMessage>
                    <Subtitle class="font-weight-bold">
                        %%overview02%%
                    </Subtitle>
                    <Card padding="3">
                        <Row>
                            <Column size="6" mediumSize="12" smallSize="12" textPosition="center" padding="2" class="mt-2 pl-4 text-sm-center text-md-center text-xl-left">
                                <div>
                                    <strong>
                                        %%overview03%%:
                                    </strong>
                                    &nbsp; {author}
                                </div>
                                <div>
                                    <strong>
                                        %%overview04%%:
                                    </strong>
                                    &nbsp; %%overview05%% {try}
                                </div>
                                <div>
                                    <strong>
                                        %%overview06%%:
                                    </strong>
                                    &nbsp; {uploadDate}
                                </div>
                                <div>
                                    <strong>
                                        %%overview07%%:
                                    </strong>
                                    &nbsp; {displayString}
                                </div>
                                <div>
                                    <strong>
                                        %%overview08%%:
                                    </strong>
                                    &nbsp; {totalTime}
                                </div>
                            </Column>
                            <Column size="6" mediumSize="12" smallSize="12" textPosition="center" padding="2" class="mt-4 pr-4 text-sm-center text-md-center text-xl-right">
                                <Button (click)="history.back();">
                                    <i class="fa fa-arrow-left fa-lg pr-2" aria-hidden="true"></i>
                                    %%overview09%%
                                </Button>
                                <RedirectButton route="overview/exportTest?testToken={token}" accent="Success">
                                    <i class="fa fa-file-archive-o fa-lg pr-2" aria-hidden="true"></i>
                                    %%overview10%%
                                </RedirectButton>
                            </Column>
                        </Row>
                    </Card>
                    <Spacing>
                    <Subtitle class="font-weight-bold">
                        %%overview11%%
                    </Subtitle>
                    <Label>
                        %%overview12%%
                    </Label>
                    <Spacing>
                    <Card>
                        <Row>
                            <OverviewColumnStat title="%%overview13%%" matches="{totalMatches}" total="{totalNotes}">
                            <OverviewColumnStat title="%%overview14%%" matches="{totalPianoMatches}" total="{totalPianoNotes}">
                            <OverviewColumnStat title="%%overview15%%" matches="{totalSinMatches}" total="{totalSinNotes}">
                            <OverviewColumnStat title="%%overview16%%" matches="{totalNaturalMatches}" total="{totalNaturalNotes}">
                            <OverviewColumnStat title="%%overview17%%" matches="{totalSosMatches}" total="{totalSosNotes}">
                        </Row>
                        <hr>
                        <Row>
                            <OverviewColumnNote notes="{notes}" skip="0">
                            <OverviewColumnNote notes="{notes}" skip="20">
                            <OverviewColumnNote notes="{notes}" skip="40">
                        </Row>
                    </Card>
                </Card>
            </Column>
        </Row>
    </Container>
</View>