<View title="%%piano00%%">
    <Container>
        <FluidRow padding="4">
            <Column size="7" padding="1">
                <Card class="h-100">
                    <Title>{displayString}</Title>
                    <Span fontSize="1.3em">
                        <strong>
                            %%piano01%%
                        </strong>
                        <Spacing>
                        %%piano02%%
                        <Spacing>
                        %%piano03%%
                        <If value="{displayMode}" equals="Full">
                            <Spacing>
                            <div>
                                %%piano04%%
                            </div>
                        </If>
                        <Spacing>
                        %%piano05%% {?noteMax} %%piano06%%
                    </Span>
                    <Spacing>
                    <div class="text-center">
                        <Piano displayMode="{displayMode}" audiosSources="{audiosSources}" toggleButton="pianoToggleButton" pianoLog="pianoLog" pianoLogTemplate="pianoLogTemplate">
                    </div>
                </Card>
            </Column>
            <Column size="4" padding="1">
                <Card padding="4" class="h-100">
                    <Title>
                        %%piano07%%
                    </Title>
                    <Card id="progressLog" padding="3">      
                        %%piano08%%: {?currentNoteType}
                        <Spacing>
                        %%piano09%% {?currentNoteIndexString} / {?notesPerTest}
                        <Spacing>
                        %%piano10%%: {?totalTime}
                    </Card>
                    <Spacing>
                    <Button id="pianoToggleButton">
                        ...
                    </Button>
                    <Spacing>
                    <Card id="pianoLog" padding="1" accent="Primary" class="Hide">
                        <Subtitle id="pianoLogTitle" class="m-2">
                            %%piano11%%
                        </Subtitle>
                        <Card id="pianoLogTemplate" padding="2" class="Hide m-1">
                        </Card>
                    </Card>
                </Card>
            </Column>
        </FluidRow>
    </Container>
</View>