<v-view title="Perfil de Usuario">
    <v-card size="10">
        <v-title-primary text="Bienvenido, Gabriela Chavarria">
        <v-action-button route="">Iniciar Prueba con Piano Interactivo</v-action-button>
        <v-action-button route="">Iniciar Prueba Sencilla</v-action-button>
        <v-action-button route="" accent="secondary">Cerrar Sesión</v-action-button>
        <v-spacing size="3">
        <v-title-primary text="Mis Resultados">
        
        <v-title-secondary text="Prueba #1 (08/20/2021 21:04:23)">

        <table class="table">
            <thead>
                <tr>
                    <th>Aciertos Totales</th>
                    <th>Aciertos Piano</th>
                    <th>Aciertos Sintéticos</th>
                    <th>Aciertos Naturales</th>
                    <th>Aciertos Sostenidos</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>60 / 60 (100%)</td>
                    <td>30 / 30 (100%)</td>
                    <td>30 / 30 (100%)</td>
                    <td>17 / 17 (100%)</td>
                    <td>13 / 13 (100%)</td>
                </tr>
            </tbody>
        </table>

        <table class="table">
            <thead>
                <tr>
                    <th>C / DO</th>
                    <th>C# / DO#</th>
                    <th>D / RE</th>
                    <th>D# / RE#</th>
                    <th>E / MI</th>
                    <th>F / FA</th>
                    <th>F# / FA#</th>
                    <th>G / SOL</th>
                    <th>G# / SOL#</th>
                    <th>A / LA</th>
                    <th>A# / LA#</th>
                    <th>B / SI</th>
                </tr>

            </thead>
            <tbody>
                <tr>
                    <td>100%</td>
                    <td>100%</td>
                    <td>100%</td>
                    <td>100%</td>
                    <td>100%</td>
                    <td>100%</td>
                    <td>100%</td>
                    <td>100%</td>
                    <td>100%</td>
                    <td>100%</td>
                    <td>100%</td>
                    <td>100%</td>
                </tr>
            </tbody>
        </table>


    </v-card>
</v-view>