<View title="Perfil de Usuario">
    <ServiceBanner>
    <Spacing>
    <Container>
        <Row>
            <Column smallSize="12" mediumSize="12" size="9" xlSize="8">
                <Card>
                    <IconifiedTitle source="profile.png">
                        Bienvenido/a, {username}
                    </IconifiedTitle>
                    <PersistentMessage>
                    <LoggedIn role="User">
                        <Label>
                            A continuación se listan las acciones que puede realizar para el rol de su perfil.
                        </Label>
                        <Spacing>
                        <RedirectButton route="piano?displayMode=Full">
                            <i class="fa fa-play fa-lg pr-2" aria-hidden="true"></i>
                            Iniciar Prueba con Piano Interactivo
                        </RedirectButton>
                        <RedirectButton route="piano?displayMode=Simple">
                            <i class="fa fa-keyboard-o fa-lg pr-2" aria-hidden="true"></i>
                            Iniciar Prueba Sencilla
                        </RedirectButton>
                        <Spacing>
                        <Title>
                            Historial de pruebas realizadas
                        </Title>
                        <If value="{noTests}" equals="true">
                            Usted no ha ha realizado ninguna prueba hasta el momento. ¿Porqué no intentas hacer una ahora mismo?
                        </If>
                        <If value="{noTests}" equals="false">
                            <Label>
                                Esta sección muestra un resumen breve de cada una de las pruebas que usted ha realizado.
                                <Spacing>
                                Puede hacer click sobre cada fila para acceder a una vista extendida con toda la información de esa prueba particular.
                            </Label>
                            <Spacing>
                            <Row>
                                <Column smallSize="12" mediumSize="12" size="12" xlSize="12" padding="1">
                                    <Card padding="2">
                                        <div class="table-responsive">
                                            <table class="table table-sm">
                                                <tr>
                                                    <th>Intento</th>
                                                    <th>Fecha de subida</th>
                                                    <th>Modo de visualización</th>
                                                    <th>Tiempo total transcurido</th>
                                                </tr>
                                                <Foreach from="{tests}" using="i">
                                                    <tr id="row-{parent.i.try}" (click)="window.location = '{host}overview?testToken={parent.i.token}'" class="Hover">
                                                        <td>
                                                            {parent.i.try}
                                                        </td>
                                                        <td>
                                                            {parent.i.uploadDate}
                                                        </td>
                                                        <td>
                                                            {parent.i.displayMode}
                                                        </td>
                                                        <td>
                                                            {parent.i.totalTime}
                                                        </td>
                                                    </tr>
                                                </Foreach>
                                            </table>
                                        </div>
                                    </Card>
                                </Column>
                            </Row>
                            <Spacing>
                        </If>
                    </LoggedIn>
                    <LoggedIn role="Admin">
                        <Title>
                            Listado de todos los usuarios
                        </Title>
                        <Label>
                            Esta sección muestra todos los usuarios registrados en el sitio web, y permite de forma rápida visualizar sus pruebas
                            <Spacing>
                            Puede hacer click sobre cada fila para acceder a una vista extendida con toda la información de ese usuario particular.
                        </Label>
                        <Spacing>
                        <Row>
                            <Column smallSize="12" mediumSize="12" size="12" xlSize="12" padding="1">
                                <Card padding="2">
                                    <div class="table-responsive">
                                        <table class="table table-sm">
                                            <tr>
                                                <th>Nombre completo</th>
                                                <th>Correo electrónico</th>
                                                <th>Rol</th>
                                                <th>Fecha de nacimiento</th>
                                                <th>Teléfono</th>
                                                <th>Género</th>
                                                <th>País</th>
                                                <th>Pruebas completas</th>
                                            </tr>
                                            <Foreach from="{users}" using="i">
                                                <tr id="{parent.random}" (click)="window.location = '{host}lookup?userToken={parent.i.token}'" class="Hover">
                                                    <td>
                                                        {parent.i.firstName} {parent.i.lastName}
                                                    </td>
                                                    <td>
                                                        {parent.i.email}
                                                    </td>
                                                    <td>
                                                        <If value="{parent.i.role}" equals="0">
                                                            Administrador
                                                        </If>
                                                        <If value="{parent.i.role}" equals="1">
                                                            Usuario
                                                        </If>
                                                    </td>
                                                    <td>
                                                        {parent.i.birthDay}
                                                    </td>
                                                    <td>
                                                        {parent.i.phone}
                                                    </td>
                                                    <td>
                                                        {parent.i.gender}
                                                    </td>
                                                    <td>
                                                        {parent.i.country}
                                                    </td>
                                                    <td>
                                                        {parent.i.tries}
                                                    </td>
                                                </tr>
                                            </Foreach>
                                        </table>
                                        <div>
                                            <RedirectButton route="profile?page=[{page}-1]" accent="Info" disabled="{isFirstPage}">&#8592;</RedirectButton>
                                            <RedirectButton route="profile?page=[{page}+1]" accent="Info" disabled="{isLastPage}">&#8594;</RedirectButton>
                                        </div>
                                    </div>
                                </Card>
                            </Column>
                        </Row>
                    </LoggedIn>
                </Card>
            </Column>
        </Row>
    </Container>
</View>