<app:view title="Recolección de información">
    <app:row>
        <app:card columnSize="12">
            <app:title-icon imageSource="question.png" text="Recolección de información">
            <app:title-secondary text="Se le pedirá que conteste el siguiente formulario sinceramente:">
            <app:paginator id="questions" numberOfPages="4" elementsPerPage="10">
                <app:row>
                    <app:col columnSize="6">
                        <app:survey source="{view:questions}" skip="({this:page}*{this:elementsPerPage})" take="({this:elementsPerPage}/2)">
                    </app:col>
                    <app:col columnSize="6">
                        <app:survey source="{view:questions}" skip="({this:page}*{this:elementsPerPage}+{this:elementsPerPage}/2)" take="({this:elementsPerPage}/2)">
                    </app:col>
                </app:row>
            </app:paginator>
        </app:card>
    </app:row>
</app:view>