<View title="%%survey00%%">
    <Container>
        <Row>
            <Column size="10">
                <Card>
                    <IconifiedTitle source="survey.png">
                        %%survey00%%
                    </IconifiedTitle>
                    <Subtitle>
                        %%survey01%%
                    </Subtitle>
                    <Label>
                        %%survey02%%
                    </Label>
                    <Spacing>
                    <Form id="surveyForm" route="survey/submit">
                        <FormPaginator form="{parent.formName}" numberOfPages="5">
                            <Survey from="{surveyQuestions}" skip="[{parent.page}*10]" take="10">
                        </FormPaginator>
                    </Form>
                </Card>
            </Column>
        </Row>
    </Container>
</View>